# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\QT\untitled1\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(718, 498)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 311, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 90, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 120, 21, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(130, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 120, 51, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(70, 90, 71, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(70, 16, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 44, 171, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 40, 41, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 0, 361, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 341, 121))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 119))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(0, 80, 301, 20))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(320, 0, 16, 101))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 10, 311, 71))
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setGeometry(QtCore.QRect(0, 100, 111, 16))
        self.checkBox.setObjectName("checkBox")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 160, 161, 141))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 0, 121, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 89, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 50, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 70, 89, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 90, 89, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 110, 89, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(170, 160, 171, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 30, 121, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_7.setGeometry(QtCore.QRect(30, 50, 131, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 70, 101, 16))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_9.setGeometry(QtCore.QRect(30, 90, 89, 16))
        self.radioButton_9.setObjectName("radioButton_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 310, 331, 41))
        self.groupBox_6.setObjectName("groupBox_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_4.setGeometry(QtCore.QRect(60, 20, 41, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_5.setGeometry(QtCore.QRect(110, 20, 51, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_6.setGeometry(QtCore.QRect(160, 20, 41, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_7.setGeometry(QtCore.QRect(210, 20, 51, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_8.setGeometry(QtCore.QRect(270, 20, 71, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 360, 161, 51))
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_11.setGeometry(QtCore.QRect(60, 20, 61, 16))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_12.setGeometry(QtCore.QRect(110, 20, 89, 16))
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 430, 211, 41))
        self.groupBox_8.setTitle("项目管理系统V1.0")
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 161, 23))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(180, 360, 141, 51))
        self.groupBox_9.setObjectName("groupBox_9")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_9)
        self.listWidget_2.setGeometry(QtCore.QRect(90, 20, 41, 16))
        self.listWidget_2.setObjectName("listWidget_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 20, 91, 16))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_13.setGeometry(QtCore.QRect(340, 150, 341, 311))
        self.groupBox_13.setObjectName("groupBox_13")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 20, 311, 101))
        self.groupBox_14.setObjectName("groupBox_14")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_9.setGeometry(QtCore.QRect(130, 0, 71, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_10.setGeometry(QtCore.QRect(210, 0, 71, 16))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_12.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_13.setGeometry(QtCore.QRect(110, 20, 71, 16))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_15.setGeometry(QtCore.QRect(60, 80, 71, 16))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_16.setGeometry(QtCore.QRect(130, 80, 71, 16))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_17.setGeometry(QtCore.QRect(210, 80, 71, 16))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_18.setGeometry(QtCore.QRect(210, 50, 71, 16))
        self.checkBox_18.setObjectName("checkBox_18")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 130, 311, 81))
        self.groupBox_15.setObjectName("groupBox_15")
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_19.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_20.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_21.setGeometry(QtCore.QRect(100, 20, 71, 16))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_22.setGeometry(QtCore.QRect(150, 20, 71, 16))
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_23.setGeometry(QtCore.QRect(200, 20, 71, 16))
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_24.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_25.setGeometry(QtCore.QRect(60, 50, 71, 16))
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_15)
        self.checkBox_26.setGeometry(QtCore.QRect(110, 50, 71, 16))
        self.checkBox_26.setObjectName("checkBox_26")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 220, 151, 80))
        self.groupBox_16.setObjectName("groupBox_16")
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkBox_27.setGeometry(QtCore.QRect(0, 20, 71, 16))
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkBox_28.setGeometry(QtCore.QRect(0, 50, 71, 16))
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkBox_29.setGeometry(QtCore.QRect(80, 20, 71, 16))
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox_16)
        self.checkBox_30.setGeometry(QtCore.QRect(80, 50, 71, 16))
        self.checkBox_30.setObjectName("checkBox_30")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_17.setGeometry(QtCore.QRect(170, 220, 151, 80))
        self.groupBox_17.setObjectName("groupBox_17")
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox_17)
        self.checkBox_31.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.checkBox_31.setObjectName("checkBox_31")
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox_17)
        self.checkBox_32.setGeometry(QtCore.QRect(60, 20, 71, 16))
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "项目基础设置"))
        self.label.setText(_translate("Dialog", "所属类别："))
        self.label_2.setText(_translate("Dialog", "参与下载的线程："))
        self.lineEdit_3.setText(_translate("Dialog", "4"))
        self.label_3.setText(_translate("Dialog", "页面访问间隔："))
        self.lineEdit_4.setText(_translate("Dialog", "200"))
        self.comboBox.setItemText(0, _translate("Dialog", "搜索项目"))
        self.label_4.setText(_translate("Dialog", "项目名称："))
        self.label_5.setText(_translate("Dialog", "项目位置："))
        self.pushButton_2.setText(_translate("Dialog", "选择"))
        self.groupBox_3.setTitle(_translate("Dialog", "搜索的关键词：（多组关键词时换行区分）"))
        self.checkBox.setText(_translate("Dialog", "从txt文件导入："))
        self.checkBox_2.setText(_translate("Dialog", "启动定期更新功能"))
        self.radioButton.setText(_translate("Dialog", "每月"))
        self.radioButton_2.setText(_translate("Dialog", "每周"))
        self.radioButton_3.setText(_translate("Dialog", "每天"))
        self.radioButton_4.setText(_translate("Dialog", "间隔"))
        self.radioButton_5.setText(_translate("Dialog", "定点"))
        self.groupBox_5.setTitle(_translate("Dialog", "重复数据的处理方式"))
        self.radioButton_6.setText(_translate("Dialog", "完全覆盖已有数据"))
        self.radioButton_7.setText(_translate("Dialog", "检查补充新增的内容"))
        self.radioButton_8.setText(_translate("Dialog", "跳过已采数据"))
        self.radioButton_9.setText(_translate("Dialog", "不判断重复"))
        self.groupBox_6.setTitle(_translate("Dialog", "采集目标"))
        self.checkBox_3.setText(_translate("Dialog", "标题"))
        self.checkBox_4.setText(_translate("Dialog", "正文"))
        self.checkBox_5.setText(_translate("Dialog", "时间"))
        self.checkBox_6.setText(_translate("Dialog", "来源"))
        self.checkBox_7.setText(_translate("Dialog", "作者"))
        self.checkBox_8.setText(_translate("Dialog", "关键词"))
        self.groupBox_7.setTitle(_translate("Dialog", "解析方式"))
        self.radioButton_10.setText(_translate("Dialog", "简单"))
        self.radioButton_11.setText(_translate("Dialog", "深度"))
        self.radioButton_12.setText(_translate("Dialog", "精细"))
        self.pushButton.setText(_translate("Dialog", "更多第自动解析的详细设置"))
        self.groupBox_9.setTitle(_translate("Dialog", "搜索时的翻页深度"))
        self.groupBox_10.setTitle(_translate("Dialog", "搜素翻页次数："))
        self.groupBox_13.setTitle(_translate("Dialog", "搜索对象"))
        self.groupBox_14.setTitle(_translate("Dialog", "新闻"))
        self.checkBox_9.setText(_translate("Dialog", "时间排序"))
        self.checkBox_10.setText(_translate("Dialog", "新闻标题"))
        self.checkBox_11.setText(_translate("Dialog", "百度"))
        self.checkBox_12.setText(_translate("Dialog", "搜狗"))
        self.checkBox_13.setText(_translate("Dialog", "360"))
        self.checkBox_14.setText(_translate("Dialog", "国搜"))
        self.checkBox_15.setText(_translate("Dialog", "中搜"))
        self.checkBox_16.setText(_translate("Dialog", "微软"))
        self.checkBox_17.setText(_translate("Dialog", "谷歌"))
        self.checkBox_18.setText(_translate("Dialog", "雅虎"))
        self.groupBox_15.setTitle(_translate("Dialog", "网页"))
        self.checkBox_19.setText(_translate("Dialog", "百度"))
        self.checkBox_20.setText(_translate("Dialog", "360"))
        self.checkBox_21.setText(_translate("Dialog", "中搜"))
        self.checkBox_22.setText(_translate("Dialog", "搜狗"))
        self.checkBox_23.setText(_translate("Dialog", "谷歌"))
        self.checkBox_24.setText(_translate("Dialog", "国搜"))
        self.checkBox_25.setText(_translate("Dialog", "雅虎"))
        self.checkBox_26.setText(_translate("Dialog", "微软"))
        self.groupBox_16.setTitle(_translate("Dialog", "论坛.博客"))
        self.checkBox_27.setText(_translate("Dialog", "搜狗论坛"))
        self.checkBox_28.setText(_translate("Dialog", "中搜论坛"))
        self.checkBox_29.setText(_translate("Dialog", "搜狗博客"))
        self.checkBox_30.setText(_translate("Dialog", "中搜博客"))
        self.groupBox_17.setTitle(_translate("Dialog", "微博"))
        self.checkBox_31.setText(_translate("Dialog", "微信"))
        self.checkBox_32.setText(_translate("Dialog", "新浪微博"))

